version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  test-api:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r api/requirements.txt
      - run:
          name: Run test and collect coverage for calculator
          command: pytest --cov=api.calculator --cov-report=xml:calculator-coverage.xml
      - run:
          name: Run test and collect coverage for smiles
          command: pytest --cov=api.smiles --cov-report=xml:smiles-coverage.xml
      - codecov/upload

workflows:
  version: 2.1
  build-test:
    jobs:
      - test-api
